services:
  loki:
    image: grafana/loki:3.6.3
    container_name: loki
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:3.2.1
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.3.0-ubuntu
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # การตั้งค่าสำหรับ Domain และ SSL
      - VIRTUAL_HOST=uat.log.manus-skill.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=uat.log.manus-skill.com
      - LETSENCRYPT_EMAIL=info@macode-solution.com
      # การตั้งค่า Grafana ให้รู้ว่ารันอยู่บน HTTPS
      - GF_SERVER_ROOT_URL=https://uat.log.manus-skill.com/
      - GF_SERVER_PROTOCOL=http # ตัว Grafana เองรัน http แต่ nginx จะครอบด้วย https
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
      - api_default # เชื่อมต่อกับ network ของ nginx-proxy
    depends_on:
      - loki

networks:
  monitoring:
    driver: bridge
  api_default:
    external: true
    name: api_default

volumes:
  grafana-data: